module "primarycluster"{
 source = "./modules"
resource_group =  "${var.resource_group}"
hostname =  "${var.hostname}"
location =  "${var.location}"
admin_username =  "${var.admin_username}"
admin_password =  "${var.admin_password}"
server =  "${var.server}"
subscription =  "${var.subscription}"
tenant =  "${var.tenant}"
client_id =  "${var.client_id}"
client_secret =  "${var.client_secret}"
owner =  "${var.owner}"
public_key =  "${var.public_key}"
servers =  "${var.servers}"
nomadworkers =  "${var.nomadworkers}"
vaultlicense =  "${var.vaultlicense}"
consullicense =  "${var.consullicense}"
enterprise =  "${var.enterprise}"
}